SELECT E.BRANCH_ID, COUNT(DISTINCT S.CAR_ID) AS INSURANCE_COUNT
FROM EMPLOYEES E
JOIN SELLINGS S ON E.ID = S.EMPLOYEE_ID
WHERE E.BRANCH_ID IN (15, 16, 17)
GROUP BY E.BRANCH_ID
ORDER BY E.BRANCH_ID;
# S.~: SELLINGS 테이블의 컬럼을 참조합니다.
# E.~: EMPLOYEES 테이블의 컬럼을 참조합니다.